version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    container_name: "questions-api"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      DB_HOST: ${DB_HOST}

